config/routes.rb
PearlSkin::Application.routes.draw do
  get "searchs/search"
  get "users/new"
  resources :countries
  resources :brands
  resources :categories
  resources :subcategories
  resources :items
  resources :comments
  resources :brand_addrs
  resources :item_addrs
  resources :users do
    member do
      get :useds
      get :favourites
      get :plans
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :useds, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :plans, only: [:create, :destroy]

  root to: 'static_pages#home'

  match 'all_brands', to: 'brands#all_brands', via: 'get'
  match 'signup', to: 'users#new', via:'get'
  match 'signin', to: 'sessions#new', via:'get'
  match 'signout', to: 'sessions#destroy', via:'delete'
  match 'show_image', to: 'items#show_image', via:'get'
  match 'show_user_items', to: 'users#show_user_items', via:'get'
  match 'show_subcategory_brand_items', to: 'subcategories#show_subcategory_brand_items', via:'get'
  match 'search', to: 'searchs#search', via:'get'

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :items, dependent: :destroy

	default_scope -> {order('step')}

	validates :name, presence: true, length: {maximum: 140}
	validates :category_id, presence: true
	validates :step, presence: true
	
	def self.find_subcategories
		Subcategory.find(:all, :order => "name").collect{|subcategory| [subcategory.name, subcategory.id]}
	end

	def subcategory_name
		Category.find(self.category_id).name+"-"+self.name
	end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController <ApplicationController
	before_action :signed_in_user, only: [:show]
  	before_action :admin_user,     only: [:index, :carete, :destroy, :update]
	def index
		#@category = Category.find(params[:id])
		@subcategories = @category.subcategories.paginate(page: params[:page]).per_page(10)
	end

	def show
		@subcategory =  Subcategory.find(params[:id])
	end

	def create
		@category = Category.find(params[:category_id])
		@subcategory = @category.subcategories.build(subcategory_params)
		begin
			if @subcategory.save
				flash[:success] = "已添加“#{@subcategory.name}”"
			else
				flash[:failed] = "添加“#{@subcategory.name}”失败"
			end
		rescue ActiveRecord::RecordNotUnique
			flash[:failed] = "该类别已存在！"
		end
		redirect_to category_path(@category.id)
	end

	def destroy
		destroy_subcategory = Subcategory.find(params[:id])
		destroy_subcategory.destroy
		flash[:success] = "已删除“#{destroy_subcategory.name}”"
		redirect_to category_path(destroy_subcategory.category_id)
	end

	def update
		@subcategory = Subcategory.find(params[:id])
		begin
			if @subcategory.update_attributes(subcategory_params)
				flash[:success] = "更新成功"
			else
				flash[:failed] = "更新失败！"
			end
		rescue ActiveRecord::RecordNotUnique
			flash[:failed] = "该类别已存在！"
		end	
		redirect_to category_path(@subcategory.category_id)
	end

  def show_subcategory_brand_items
    brand_id = params[:brand_id]
    subcategory_id = params[:subcategory_id]
    @items = Item.where("subcategory_id=#{subcategory_id}").where("brand_id=#{brand_id}").order('item_english')
    
    respond_to do |format|
      # format.html { redirect_to item_path(@item_id) }
      format.js
    end
  end

	private
		def subcategory_params
			params.require(:subcategory).permit(:name, :step)
		end
end

app/views/subcategories/_subcategory.html.erb
<li>
	<span class = "content">
		<%= form_for(subcategory) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class="category_form">
				<td>
					<tr>
						<%= f.text_field :name %>
					</tr>
					<tr>
						<%= f.text_area :step, placeholder: "步骤..."  %>
					</tr>
				</td>
			</div>
			<%= f.submit "保存", class: "btn btn-primary" %>
			<%= link_to "删除", subcategory,  method: :delete,
									data: { confirm: "确定删除？"},
									title: subcategory.name %>
		<% end %>
	</span>
</li>

app/views/subcategories/show.html.erb
<% provide(:title, @subcategory.subcategory_name) %>

<div class="row">
	<aside class="span3">
		<section>
			<span class="item_brand">
				<%= @subcategory.subcategory_name %>
			</span>
		</section>
		<section>
			<% @item_brands = Item.includes(:brand).where("subcategory_id=#{@subcategory.id}").order('brands.brand_english').group(:brand_id, :brand_english).count %>
			<% @item_brands.each do |item_brand| %>
				<%= link_to show_subcategory_brand_items_path(:brand_id => item_brand[0][0], :subcategory_id => @subcategory.id) , :remote => true do%>
					<h4>
						<%= Brand.find(item_brand[0][0]).brand_name %>(<%= item_brand[1] %>)
						<br>
					</h4>
				<% end %>
			<% end %>
		</section>
	</aside>
	<div id = "subcategory_brand_items" class="span9">
		<% @subcategories_items = Item.includes(:brand).where("subcategory_id=#{@subcategory.id}").order('brands.brand_english, item_english').paginate(page: params[:page]).per_page(15) %>
		<%= will_paginate @subcategories_items, :previous_label => "上一页", :next_label => "下一页" %>
		<%= render 'shared/item_gridview' , object: @subcategories_items %>
		<%= will_paginate @subcategories_items, :previous_label => "上一页", :next_label => "下一页" %>
	</div>
</div>

app/views/subcategories/show_subcategory_brand_items.js.erb
$("#subcategory_brand_items").html("<%= escape_javascript(render 'shared/item_gridview', object:@items) %>");