config/routes.rb
PearlSkin::Application.routes.draw do
  get "searchs/search"
  get "users/new"
  resources :countries
  resources :brands
  resources :categories
  resources :subcategories
  resources :items
  resources :comments
  resources :brand_addrs
  resources :item_addrs
  resources :users do
    member do
      get :useds
      get :favourites
      get :plans
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :useds, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :plans, only: [:create, :destroy]

  root to: 'static_pages#home'

  match 'all_brands', to: 'brands#all_brands', via: 'get'
  match 'signup', to: 'users#new', via:'get'
  match 'signin', to: 'sessions#new', via:'get'
  match 'signout', to: 'sessions#destroy', via:'delete'
  match 'show_image', to: 'items#show_image', via:'get'
  match 'show_user_items', to: 'users#show_user_items', via:'get'
  match 'show_subcategory_brand_items', to: 'subcategories#show_subcategory_brand_items', via:'get'
  match 'search', to: 'searchs#search', via:'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_item_gridview.html.erb
<article id = "featuredProducts" class="grids">
	<div id = "featured-products">
		<div class="flex-box-3 item">
			<% counter = 1 %>
			<% object.each do |item| %>
				<% if counter%3 == 1 %>
					<% colmID="itemGridbty firstCol" %>
				<% elsif counter%3 == 2 %>
					<% colmID="itemGridbty centerCol" %>
				<% else %>
					<% colmID="itemGridbty lastCol" %>
				<% end %>
				<div class="<%= colmID %>" >
					<%= render 'shared/single_item' , object:item %>
				</div>
				<% counter = counter+1 %>
			<% end %>
		</div>
	</div>
</article>

app/views/shared/_single_item.html.erb
<div class="prodImg">
	<% if !object.image.nil? %>
		<%= image_tag url_for(:controller => "items", :action => "show_image", :id => object.id), size: "220" %>
	<% end %>
</div>
<div>
	<div class="info">
		<span class="productDetails">
			<% brand = Brand.find(object.brand_id) %>
			<span class="brandName"><%= link_to brand.brand_english, brand_path(brand.id) %></span>
			<span class="proddesc"><%= link_to object.item_english, item_path(object.id) %></span>
			<span class="proddesc">
				 -
				<%= brand.brand_chinese+object.item_chinese%>
			</span>
			<br>
			<span class="prodCharacter">
				<% if !object.character.nil? && object.character!=""%>
					<%= object.character %>
				<% end %>
			</span>
		</span>
	</div>
</div>